// Generated by CoffeeScript 2.7.0
(function() {

  /*

  Shiny Bloon effects

  Effect             Prob.     Description
  -------------      ------    -----------
  Bloon Bonus        60.00%    Give a huge bonus of Bloons.
  Rain Dance         33.50%    Gives both clicking and GpS a x12 boost for 70.4 seconds.
  Click Frenzy        5.00%    Gives clicking a x704 GpC boost for 7.04 seconds.
  Click EXP Frenzy    0.95%    Gives clicking a x10 EXP/click boost for 20 seconds.
  Level Up            0.45%    Levels the Bloon up once.
                      0.10%

  */
  var ETERNAL_BLOON_FALLBACK, ETERNAL_BLOON_IMAGE, Generator, Item, PlusMarker, _import_save_0_05, _import_save_0_10, animate_plus_markers, ball01, ball02, ball99, basedata, battle, bitfield_to_sstr, bitmap, bloon, bloon_image, bombshooter, boomerangthrower, click1, cursor, def, export_save, gcm1, gcm2, gcm3, gcm4, gcm5, gen, generator_image_url, generator_upgrade_defs, generators, gens, gluegunner, goodra, hexstr, icetower, import_save, init_cooldown_time, init_input, item_ids, itemlist, items, j, k, l, last_update_time, len1, len2, len3, load_save_from_local_storage, monkey, monkeyace, monkeyapprentice, monkeybuccaneer, monkeyengineer, monkeysub, ngens, ninjamonkey, number_format_load_codes, number_format_save_codes, plus_marker_anims, plus_marker_distance, plus_marker_id, plus_marker_origradius, plus_markers, recalc, recalc_gpc, recalc_gps, regenerate_tooltips, sanitize_number_format, save_to_local_storage, set_image_with_fallback, settings, shiny_bloon, sliggoo, snipermonkey, spikefactory, sstr_to_bitfield, start_if_loaded, startup, supermonkey, tackshooter, update, updateF, update_all_numbers, update_language, update_numbers, wiki_image, youngsterpocalypse,
    indexOf = [].indexOf,
    hasProp = {}.hasOwnProperty;

  basedata = {
    version: "0.354 (pre-alpha)",
    game_started: false,
    bloons: 0,
    total_bloons: 0, // total bloons, counting ones used in purchases
    total_total_bloons: 0, // total bloons, counting ones used in reset
    play_time: 0, // play time in seconds of current session
    total_play_time: 0, // total play time over all sessions
    last_save_time: new Date(), // date and time of last save, for perfect idle calc
    gps: 0,
    expps: 0,
    gpc: 1,
    sliggoo_gpsmult: 1.0,
    raindance_mult: 1.0,
    frenzy_clickmult: 1.0,
    clicks: 0, // number of times the Great Bloon was clicked
    total_clicks: 0,
    earn: function(n) {
      this.bloons += n;
      this.total_bloons += n;
      return this.total_total_bloons += n;
    },
    click: function() {
      var gain;
      if (!this.game_started) {
        this.game_started = true;
      }
      gain = this.gpc;
      this.earn(gain);
      this.clicks += 1;
      this.total_clicks += 1;
      bloon.gain_exp(bloon.level);
      return gain;
    },
    update: function(ms) {
      var exp_gain, gain;
      gain = this.gps * ms / 1000;
      this.earn(gain);
      exp_gain = this.expps * ms / 1000;
      bloon.gain_exp(exp_gain);
      if (this.game_started) {
        this.play_time += ms;
        return this.total_play_time += ms;
      }
    },
    reset: function() {
      var generator, item, j, k, len1, len2;
      // calculate prestige bonuses
      sliggoo.gain_exp(this.total_bloons / 1e12);
      goodra.gain_exp(bloon.exp / 1e4);
      // Sliggoo gives a GPS multiplier boost.
      this.sliggoo_gpsmult = 1.0 + 0.1 * sliggoo.level;
      // Goodra raises the level cap.
      bloon.level_cap = 1000 + goodra.level;
      this.bloons = 0;
      this.total_bloons = 0;
      // @total_total_bloons is untouched.
      bloon.exp = 0;
      bloon.level = 1;
      bloon.next_lv_exp = 100;
      bloon.lv_total_exp = 0;
      this.game_started = false;
      this.play_time = 0;
      this.clicks = 0;
      for (j = 0, len1 = generators.length; j < len1; j++) {
        generator = generators[j];
        generator.count = 0;
        generator.cost = generator.base_cost;
        generator.level = 1;
        generator.upgrades = [];
      }
      for (k = 0, len2 = items.length; k < len2; k++) {
        item = items[k];
        item.bought = false;
      }
      recalc();
      update_all_numbers();
      return regenerate_tooltips();
    }
  };

  // DEBUG: expose basedata to access variables.
  this.basedata = basedata;

  settings = {
    audio: true,
    music: true,
    number_format: "full"
  };

  this.settings = settings;

  bloon_image = function(fill, stroke = "%238aa4ff") {
    return `data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 180 220'><defs><radialGradient id='g' cx='60%25' cy='25%25' r='70%25'><stop offset='0%25' stop-color='%23ffffff' stop-opacity='.75'/><stop offset='40%25' stop-color='${fill}'/><stop offset='100%25' stop-color='${fill}' stop-opacity='.82'/></radialGradient></defs><ellipse cx='90' cy='84' rx='68' ry='76' fill='url(%23g)' stroke='${stroke}' stroke-width='8'/><path d='M78 155h24l-12 40z' fill='${fill}' stroke='${stroke}' stroke-width='6' stroke-linejoin='round'/></svg>`;
  };

  wiki_image = function(filename) {
    return `https://bloons.fandom.com/wiki/Special:Redirect/file/${filename}`;
  };

  set_image_with_fallback = function(selector, sources) {
    var $img, timeout, token, try_source;
    $img = $(selector);
    if (!$.isArray(sources)) {
      sources = [sources];
    }
    token = new Date().getTime() + Math.random();
    timeout = null;
    $img.data("imageToken", token);
    try_source = function(index) {
      if ($img.data("imageToken") !== token) {
        return;
      }
      if (index >= sources.length) {
        return;
      }
      if (timeout) {
        window.clearTimeout(timeout);
      }
      $img.off(".battleImage");
      timeout = window.setTimeout((function() {
        return try_source(index + 1);
      }), 3500);
      $img.one("load.battleImage", function() {
        return window.clearTimeout(timeout);
      });
      $img.one("error.battleImage", function() {
        window.clearTimeout(timeout);
        return try_source(index + 1);
      });
      return $img.attr("src", sources[index]);
    };
    return try_source(0);
  };

  ETERNAL_BLOON_IMAGE = "https://static.wikia.nocookie.net/b__/images/0/02/TheEternal_CardArt.png/revision/latest?cb=20250513134352&path-prefix=bloons";

  ETERNAL_BLOON_FALLBACK = "data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 240 260'><defs><radialGradient id='g' cx='58%25' cy='24%25' r='72%25'><stop offset='0%25' stop-color='%23f8fff3'/><stop offset='20%25' stop-color='%238cff88'/><stop offset='62%25' stop-color='%232cb7ef'/><stop offset='100%25' stop-color='%233d49b7'/></radialGradient><filter id='glow'><feGaussianBlur stdDeviation='5' result='b'/><feMerge><feMergeNode in='b'/><feMergeNode in='SourceGraphic'/></feMerge></filter><linearGradient id='fog' x1='0' x2='1'><stop offset='0%25' stop-color='%2336f8ff' stop-opacity='.25'/><stop offset='50%25' stop-color='%23c9ffff' stop-opacity='.72'/><stop offset='100%25' stop-color='%2336f8ff' stop-opacity='.25'/></linearGradient></defs><rect width='240' height='260' fill='%2325303c'/><path d='M0 174c48-22 72 16 120-5 50-22 82 17 120-5v96H0z' fill='url(%23fog)'/><ellipse cx='120' cy='100' rx='80' ry='86' fill='url(%23g)' stroke='%23f6ff62' stroke-width='9' filter='url(%23glow)'/><circle cx='150' cy='60' r='12' fill='%23f5fff7'/><path d='M56 100c24-37 51-37 64 0 13 37 40 37 64 0M56 100c24 37 51 37 64 0 13-37 40-37 64 0' fill='none' stroke='%23fff765' stroke-width='14' stroke-linecap='round' filter='url(%23glow)'/><path d='M102 181h36l-18 42z' fill='%233cb6e8' stroke='%23f6ff62' stroke-width='7' stroke-linejoin='round'/><g stroke='%233cecff' stroke-width='7' fill='none' opacity='.55'><path d='M10 142c18-28 34-28 52 0 18 28 34 28 52 0'/><path d='M126 142c18-28 34-28 52 0 18 28 34 28 52 0'/></g></svg>";

  battle = {
    active: false,
    timer: 0,
    duration: 30000,
    hp: 0,
    max_hp: 0,
    tap_mult: 1,
    bps_mult: 1,
    defeated: 0,
    current_index: 0,
    eternal_stage: 0,
    bloons: [
      {
        name: "Blue Bloon",
        hp: 1000,
        tap_reward: 0.01,
        bps_reward: 0.005,
        image: [wiki_image("BTD6BlueBloon.png"),
      wiki_image("Blue_Bloon_BTD6.png"),
      bloon_image("%233e7bff",
      "%238aa4ff")]
      },
      {
        name: "Green Bloon",
        hp: 7500,
        tap_reward: 0.015,
        bps_reward: 0.0075,
        image: [wiki_image("BTD6GreenBloon.png"),
      wiki_image("Green_Bloon_BTD6.png"),
      bloon_image("%2337d45f",
      "%2382f59a")]
      },
      {
        name: "Yellow Bloon",
        hp: 50000,
        tap_reward: 0.02,
        bps_reward: 0.01,
        image: [wiki_image("BTD6YellowBloon.png"),
      wiki_image("Yellow_Bloon_BTD6.png"),
      bloon_image("%23ffd83f",
      "%23fff187")]
      },
      {
        name: "Pink Bloon",
        hp: 350000,
        tap_reward: 0.025,
        bps_reward: 0.0125,
        image: [wiki_image("BTD6PinkBloon.png"),
      wiki_image("Pink_Bloon_BTD6.png"),
      bloon_image("%23ff5fb7",
      "%23ff9fd4")]
      },
      {
        name: "Black Bloon",
        hp: 2500000,
        tap_reward: 0.03,
        bps_reward: 0.015,
        image: [wiki_image("BTD6BlackBloon.png"),
      wiki_image("Black_Bloon_BTD6.png"),
      bloon_image("%2324242a",
      "%23757582")]
      },
      {
        name: "White Bloon",
        hp: 15000000,
        tap_reward: 0.035,
        bps_reward: 0.0175,
        image: [wiki_image("BTD6WhiteBloon.png"),
      wiki_image("White_Bloon_BTD6.png"),
      bloon_image("%23f7f7f7",
      "%23c9d8ff")]
      },
      {
        name: "Lead Bloon",
        hp: 100000000,
        tap_reward: 0.04,
        bps_reward: 0.02,
        image: [wiki_image("BTD6LeadBloon.png"),
      wiki_image("Lead_Bloon_BTD6.png"),
      bloon_image("%23838383",
      "%23c8c8c8")]
      },
      {
        name: "Zebra Bloon",
        hp: 750000000,
        tap_reward: 0.045,
        bps_reward: 0.0225,
        image: [wiki_image("BTD6ZebraBloon.png"),
      wiki_image("Zebra_Bloon_BTD6.png"),
      bloon_image("%23ffffff",
      "%23161616")]
      },
      {
        name: "Rainbow Bloon",
        hp: 5000000000,
        tap_reward: 0.05,
        bps_reward: 0.025,
        image: [wiki_image("BTD6RainbowBloon.png"),
      wiki_image("Rainbow_Bloon_BTD6.png"),
      bloon_image("%23ff4646",
      "%23864cff")]
      },
      {
        name: "Ceramic Bloon",
        hp: 40000000000,
        tap_reward: 0.06,
        bps_reward: 0.03,
        image: [wiki_image("BTD6CeramicBloon.png"),
      wiki_image("Ceramic_Bloon_BTD6.png"),
      bloon_image("%23c7803c",
      "%23ffd17d")]
      },
      {
        name: "MOAB",
        hp: 250000000000,
        tap_reward: 0.075,
        bps_reward: 0.04,
        image: "https://static.wikia.nocookie.net/b__/images/b/ba/BTD6MOAB.png/revision/latest?cb=20180809063308&path-prefix=bloons"
      },
      {
        name: "BFB",
        hp: 2500000000000,
        tap_reward: 0.1,
        bps_reward: 0.055,
        image: wiki_image("BTD6BFB.png")
      },
      {
        name: "ZOMG",
        hp: 25000000000000,
        tap_reward: 0.13,
        bps_reward: 0.07,
        image: wiki_image("BTD6ZOMG.png")
      },
      {
        name: "B.A.D",
        hp: 250000000000000,
        tap_reward: 0.18,
        bps_reward: 0.1,
        image: "https://static.wikia.nocookie.net/b__/images/4/41/BTD63DBAD.png/revision/latest?cb=20190620201902&path-prefix=bloons"
      }
    ],
    eternal_base_hp: 250000000000000 * 21,
    eternal_hp_scale: 7.5,
    eternal_tap_reward: 0.10,
    eternal_bps_reward: 0.05,
    current_bloon: function() {
      var stage;
      if (this.current_index >= this.bloons.length) {
        stage = this.eternal_stage + 1;
        return {
          name: `Eternal Bloon Stage ${stage}`,
          hp: this.eternal_base_hp * Math.pow(this.eternal_hp_scale, this.eternal_stage),
          tap_reward: this.eternal_tap_reward + this.eternal_stage * 0.01,
          bps_reward: this.eternal_bps_reward + this.eternal_stage * 0.005,
          image: [ETERNAL_BLOON_IMAGE, ETERNAL_BLOON_FALLBACK],
          eternal: true
        };
      }
      return this.bloons[Math.min(this.current_index, this.bloons.length - 1)];
    },
    recalculate_rewards: function() {
      var i, j, k, ref, ref1, results, stage;
      this.tap_mult = 1;
      this.bps_mult = 1;
      for (i = j = 0, ref = Math.min(this.defeated, this.bloons.length); (0 <= ref ? j < ref : j > ref); i = 0 <= ref ? ++j : --j) {
        this.tap_mult += this.bloons[i].tap_reward;
        this.bps_mult += this.bloons[i].bps_reward;
      }
      if (this.eternal_stage > 0) {
        results = [];
        for (stage = k = 1, ref1 = this.eternal_stage; (1 <= ref1 ? k <= ref1 : k >= ref1); stage = 1 <= ref1 ? ++k : --k) {
          this.tap_mult += this.eternal_tap_reward + (stage - 1) * 0.01;
          results.push(this.bps_mult += this.eternal_bps_reward + (stage - 1) * 0.005);
        }
        return results;
      }
    },
    start: function() {
      var bloon;
      if (!($("#battle_tab").hasClass("active") && $("#battle_start").is(":visible"))) {
        return this.render_status("Open the Battle tab before starting a boss fight.");
      }
      if (this.active) {
        return this.render_status(`Already fighting ${this.current_bloon().name}!`);
      }
      bloon = this.current_bloon();
      this.active = true;
      this.timer = this.duration;
      this.max_hp = bloon.hp;
      this.hp = this.max_hp;
      this.render_status(`Fight started: ${bloon.name}. Pop it before time runs out.`);
      return this.render();
    },
    tap: function() {
      if (!this.active) {
        return;
      }
      return this.damage(Math.max(1, basedata.gpc));
    },
    damage: function(n) {
      if (!this.active) {
        return;
      }
      if (!(isFinite(n) && n > 0)) {
        return;
      }
      this.hp -= n;
      if (this.hp <= 0) {
        return this.win();
      } else {
        return this.render();
      }
    },
    win: function() {
      var bloon, name;
      bloon = this.current_bloon();
      name = bloon.name;
      this.active = false;
      this.defeated += 1;
      if (bloon.eternal) {
        this.eternal_stage += 1;
      } else {
        this.current_index = Math.min(this.current_index + 1, this.bloons.length);
      }
      this.tap_mult += bloon.tap_reward;
      this.bps_mult += bloon.bps_reward;
      $("#battle_trophies").append(`<div class='battle-trophy'>${name}<br/>+${(bloon.tap_reward * 100).toFixed(1)}% Tap, +${(bloon.bps_reward * 100).toFixed(1)}% BPS</div>`);
      this.render_status(`Victory! ${name} defeated. Next up: ${this.current_bloon().name}.`);
      this.render();
      return recalc();
    },
    lose: function() {
      this.active = false;
      this.render_status(`Time up! ${this.current_bloon().name} escaped.`);
      return this.render();
    },
    update: function(ms) {
      if (!this.active) {
        return;
      }
      this.timer -= ms;
      if (this.timer <= 0) {
        return this.lose();
      }
      return this.damage(basedata.gps * ms / 1000);
    },
    render_status: function(message) {
      return $("#battle_status").html(message);
    },
    render: function() {
      var bloon, sources;
      bloon = this.current_bloon();
      sources = bloon.image;
      $("#battle_target").html(bloon.name);
      set_image_with_fallback("#battle_bloon_img", sources);
      set_image_with_fallback("#great_bloon", this.defeated > 0 ? sources : "img/Bloon.png");
      $("#battle_timer").html((Math.max(0, this.timer) / 1000).toFixed(1) + "s");
      $("#battle_hp").attr("max", this.max_hp || bloon.hp);
      $("#battle_hp").attr("value", Math.max(0, this.hp || bloon.hp));
      $("#battle_hp_value").html(reprnum(Math.ceil(Math.max(0, this.hp || bloon.hp))) + " / " + reprnum(this.max_hp || bloon.hp) + " HP");
      return $("#battle_tap").prop("disabled", !this.active);
    }
  };

  this.battle = battle;

  bloon = {
    exp: 0,
    level: 1,
    next_lv_exp: 100,
    lv_total_exp: 0,
    level_cap: 100,
    level_up: function() {
      this.level += 1;
      this.lv_total_exp += this.next_lv_exp;
      this.next_lv_exp = this.level * this.level * 100;
      recalc_gpc();
      return update_all_numbers();
    },
    gain_exp: function(exp) {
      var results;
      this.exp += exp;
      if (this.level >= this.level_cap && this.exp > this.lv_total_exp) {
        this.exp = this.lv_total_exp;
      }
      results = [];
      while (this.exp >= this.lv_total_exp + this.next_lv_exp && this.level < this.level_cap) {
        results.push(this.level_up());
      }
      return results;
    }
  };

  sliggoo = {
    exp: 0,
    level: 0,
    next_lv_exp: 25,
    lv_total_exp: 0,
    level_up: function() {
      this.level += 1;
      this.lv_total_exp += this.next_lv_exp;
      return this.next_lv_exp = (this.level + 5) * (this.level + 5);
    },
    gain_exp: function(exp) {
      var results;
      this.exp += exp;
      results = [];
      while (this.exp >= this.lv_total_exp + this.next_lv_exp) {
        results.push(this.level_up());
      }
      return results;
    }
  };

  goodra = {
    exp: 0,
    level: 0,
    next_lv_exp: 1000,
    lv_total_exp: 0,
    level_up: function() {
      this.level += 1;
      this.lv_total_exp += this.next_lv_exp;
      return this.next_lv_exp = this.level * 30 + 1000;
    },
    gain_exp: function(exp) {
      var results;
      this.exp += exp;
      results = [];
      while (this.exp >= this.lv_total_exp + this.next_lv_exp) {
        results.push(this.level_up());
      }
      return results;
    }
  };

  this.bloon = bloon;

  this.sliggoo = sliggoo;

  this.goodra = goodra;

  gens = {};

  generators = [];

  Generator = class Generator {
    constructor(name) {
      this.name = name;
      this.display_name = name;
      this.description = "";
      this.image = name;
      this.legacy_names = [];
      this.base_gps = 0.0;
      this.premult_gps = 0.0;
      this.gps = 0.0;
      this.level = 1;
      this.level_mult = 1.0;
      this.base_cost = 15;
      this.cost = this.base_cost;
      this.lvup_cost = this.base_cost * 100;
      this.count = 0;
      this.cost_f = function(n) {
        return Math.floor(this.base_cost * Math.pow(n + 10, Math.log(n + 10) / Math.log(10)) / 10);
      };
      gens[name] = this;
      generators.push(this);
    }

    buy(n) {
      var i, j, ref;
      for (i = j = 1, ref = n; (1 <= ref ? j <= ref : j >= ref); i = 1 <= ref ? ++j : --j) {
        if (basedata.bloons < this.cost) {
          recalc();
          return i - 1;
        }
        basedata.bloons -= this.cost;
        this.count += 1;
        this.cost = this.cost_f(this.count);
      }
      recalc();
      return n;
    }

    sell(n) {
      var i, j, ref;
      for (i = j = 1, ref = n; (1 <= ref ? j <= ref : j >= ref); i = 1 <= ref ? ++j : --j) {
        if (this.count <= 0) {
          recalc();
          return i - 1;
        }
        this.count -= 1;
        this.cost = this.cost_f(this.count);
        basedata.bloons += this.cost * 0.25;
      }
      recalc();
      return n;
    }

    levelup() {
      if (basedata.bloons < this.lvup_cost) {
        return false;
      }
      basedata.bloons -= this.lvup_cost;
      this.level += 1;
      this.lvup_cost = this.base_cost * 100 * Math.pow(1.35, this.level - 1);
      recalc();
      return true;
    }

    show_tooltip() {
      return $(`#${this.name}`).qtip("lol");
    }

    set_base_cost(cost) {
      this.base_cost = cost;
      return this.lvup_cost = this.base_cost * 100;
    }

    set_theme(display_name, description, image, legacy_names = []) {
      var j, legacy_name, len1, results;
      this.display_name = display_name;
      this.description = description;
      this.image = image;
      this.legacy_names = legacy_names;
      results = [];
      for (j = 0, len1 = legacy_names.length; j < len1; j++) {
        legacy_name = legacy_names[j];
        results.push(gens[legacy_name] = this);
      }
      return results;
    }

  };

  // actual generator data
  cursor = new Generator("cursor");

  cursor.base_gps = 0.2;

  cursor.set_base_cost(15);

  cursor.set_theme("Cursor", "A helping cursor that pops a tiny trickle of Bloons.", "cursor");

  // repl. time: 100 s
  monkey = new Generator("monkey");

  monkey.base_gps = 1.0;

  monkey.set_base_cost(100);

  monkey.set_theme("Dart Monkey", "A lil' Dart Monkey who is trained to pop and capture Bloons.", "monkey");

  // repl. time: 100 s
  tackshooter = new Generator("tackshooter");

  tackshooter.base_gps = 5.0;

  tackshooter.set_base_cost(500);

  tackshooter.set_theme("Tack Shooter", "A tower which shoots eight tacks in adjacent volleys to pop numerous Bloons.", "TackShooter", ["daycare"]);

  // repl. time: 120 s
  snipermonkey = new Generator("snipermonkey");

  snipermonkey.base_gps = 20.0;

  snipermonkey.set_base_cost(2500);

  snipermonkey.set_theme("Sniper Monkey", "A sniper monkey that can snipe bloons anywhere even if they try to attack.", "SniperMonkey", ["reserve"]);

  // repl. time: 150 s
  bombshooter = new Generator("bombshooter");

  bombshooter.base_gps = 80.0;

  bombshooter.set_base_cost(15000);

  bombshooter.set_theme("Bomb Shooter", "A cannon which shoots bombs that detonate on contact, destroying Bloon layers open.", "BombShooter", ["farm"]);

  // repl. time: 200 s
  boomerangthrower = new Generator("boomerangthrower");

  boomerangthrower.base_gps = 250.0;

  boomerangthrower.set_base_cost(50000);

  boomerangthrower.set_theme("Boomerang Thrower", "A jungle monkey who throws curving boomerangs that pop any Bloons they touch.", "BoomerangThrower", ["fountain"]);

  // repl. time: 280 s
  gluegunner = new Generator("gluegunner");

  gluegunner.base_gps = 1000.0;

  gluegunner.set_base_cost(350000);

  gluegunner.set_theme("Glue Gunner", "A monkey who glues Bloons in place, then corrodes their layers with ease.", "GlueGunner", ["cave"]);

  // repl. time: 400 s
  icetower = new Generator("icetower");

  icetower.base_gps = 4000.0;

  icetower.set_base_cost(2000000);

  icetower.set_theme("Ice Tower", "A monkey with the powers of ice, stalling Bloons in freezing blocks.", "IceTower", ["trench"]);

  // repl. time: 600 s
  ninjamonkey = new Generator("ninjamonkey");

  ninjamonkey.base_gps = 18000;

  ninjamonkey.set_base_cost(18000000);

  ninjamonkey.set_theme("Ninja Monkey", "A ninja trained to assassinate Bloons with shurikens and advanced Camo detection.", "NinjaMonkey", ["arceus"]);

  // repl. time: 1111 s
  monkeybuccaneer = new Generator("monkeybuccaneer");

  monkeybuccaneer.base_gps = 75000;

  monkeybuccaneer.set_base_cost(100000000);

  monkeybuccaneer.set_theme("Monkey Buccaneer", "A boat monkey ready to plunder Bloons with cannons, darts, and piracy.", "MonkeyBuccaneer.svg", ["rngabuser"]);

  // repl. time: 1024 s
  monkeyapprentice = new Generator("monkeyapprentice");

  monkeyapprentice.base_gps = 275000;

  monkeyapprentice.set_base_cost(1000000000);

  monkeyapprentice.set_theme("Monkey Apprentice", "A wizard monkey whose fire and power magic bewitch and destroy Bloons.", "MonkeyApprentice", ["cloninglab"]);

  // repl. time: 1260 s
  monkeysub = new Generator("monkeysub");

  monkeysub.base_gps = 1350000;

  monkeysub.set_base_cost(15000000000);

  monkeysub.set_theme("Monkey Sub", "A submarine monkey that fires homing barbed torpedarts at Bloons.", "MonkeySub.svg", ["church"]);

  // repl. time: 1600 s
  monkeyace = new Generator("monkeyace");

  monkeyace.base_gps = 86500000;

  monkeyace.set_base_cost(300000000000);

  monkeyace.set_theme("Monkey Ace", "A monkey pilot who throws out powerful dart volleys from above.", "MonkeyAce.svg", ["gcminer"]);

  // repl. time: 32768 s
  spikefactory = new Generator("spikefactory");

  spikefactory.base_gps = 750000000;

  spikefactory.set_base_cost(5000000000000);

  spikefactory.set_theme("Spike Factory", "A mechanical tower that lays spikes to shred Bloons that pass through.", "SpikeFactory.svg", ["photoncollider"]);

  // repl. time: 86400 s
  monkeyengineer = new Generator("monkeyengineer");

  monkeyengineer.base_gps = 40000000000;

  monkeyengineer.set_base_cost(30e15);

  monkeyengineer.set_theme("Monkey Engineer", "An ingenious monkey who invents sentry turrets and attacks with a nail gun.", "MonkeyEngineer.svg");

  supermonkey = new Generator("supermonkey");

  supermonkey.base_gps = 800000000000;

  supermonkey.set_base_cost(860e15);

  supermonkey.set_theme("Super Monkey", "A powerful monkey who throws darts hypersonically fast to destroy MOAB-class Bloons.", "SuperMonkey");

  // create a list of the above generators
  ngens = [tackshooter, snipermonkey, bombshooter, boomerangthrower, gluegunner, icetower, ninjamonkey, monkeybuccaneer, monkeyapprentice, monkeysub, monkeyace, spikefactory, monkeyengineer, supermonkey];

// create a dictionary by name so they're more easily searchable
  for (j = 0, len1 = generators.length; j < len1; j++) {
    gen = generators[j];
    gen.cost = gen.base_cost;
  }

  generator_image_url = function(image) {
    if (/^(https?:|data:)/.test(image)) {
      return image;
    }
    if (/\.(png|gif|svg)$/i.test(image)) {
      return `img/${image}`;
    }
    return `img/${image}.png`;
  };

  init_input = function() {
    var generator, k, l, len2, len3;
    $(".nano").nanoScroller();
// populate the generator pane
    for (k = 0, len2 = ngens.length; k < len2; k++) {
      generator = ngens[k];
      $("#generators").append(`<div class='generator' id='${generator.name}'></div>`);
      $(`#${generator.name}`).append('<div class="generator-info"></div>');
      $(`#${generator.name}`).css("background-image", `url('${generator_image_url(generator.image)}')`);
      $(`#${generator.name} .generator-info`).append(`<span class='generator-count' id='${generator.name}_count'></span><br /> Next: <span class='generator-cost' id='${generator.name}_cost'>${reprnum(generator.base_cost, "short")}</span>`);
    }
    if ($(window).width() >= 1024) {
      for (l = 0, len3 = generators.length; l < len3; l++) {
        generator = generators[l];
        $(`#${generator.name}`).click((function(name) {
          return function() {
            return gens[name].buy(1);
          };
        })(generator.name));
      }
    }
    // if on a mobile platform, clicking on tooltips shouldn't autobuy.
    $("#bloon_container").mousedown(function(e) {
      var plus_marker;
      return plus_marker = new PlusMarker(`+${reprnum(Math.floor(basedata.click()))}`, e.clientX - 10 + Math.random() * 20, e.clientY - 10 + Math.random() * 20);
    });
    $("#bloon_container").contextmenu(function() {
      return false;
    });
    $("#bloon_container").mousedown(function() {
      $("#great_bloon").css("width", "96%");
      return $("#great_bloon").css("top", "2%");
    });
    $("#bloon_container").mouseup(function() {
      $("#great_bloon").css("width", "100%");
      return $("#great_bloon").css("top", "0%");
    });
    $("#export_save_button").click(function() {
      var a;
      a = export_save();
      $("#export_save").show();
      $("#export_save_string").val(a);
      $("#export_qr_code")[0].getContext("2d").clearRect(0, 0, 200, 200);
      return $("#export_qr_code").qrcode({
        text: a
      });
    });
    $(".menu-tab").click(function() {
      var target;
      target = $(this).attr("data-tab");
      $(".menu-tab").removeClass("active");
      $(this).addClass("active");
      $(".menu-panel").removeClass("active");
      return $(`#${target}`).addClass("active");
    });
    $("#battle_start").click(function() {
      return battle.start();
    });
    $("#battle_tap").click(function() {
      return battle.tap();
    });
    // settings tab
    $("#settings_audio").change(function() {
      settings.audio = $(this).is(":checked");
      return save_to_local_storage();
    });
    $("#settings_music").change(function() {
      settings.music = $(this).is(":checked");
      return save_to_local_storage();
    });
    $("#settings_number_format").change(function() {
      settings.number_format = $(this).val();
      update_all_numbers();
      battle.render();
      return save_to_local_storage();
    });
    $("#settings_reset_progress").click(function() {
      if (window.confirm && !window.confirm("Reset all progress? This cannot be undone.")) {
        return false;
      }
      window.localStorage["gc2.savefile"] = "";
      return window.location.reload();
    });
    $("#about_close").click(function() {
      return $("#about").hide();
    });
    return $("#export_close").click(function() {
      return $("#export_save").hide();
    });
  };

  items = {};

  itemlist = [];

  item_ids = {};

  Item = class Item {
    constructor(name, id) {
      this.name = name;
      this.display_name = "";
      this.description = "";
      this.caption = "";
      this.id = id;
      this.cost = 0;
      this.bought = false;
      this.locked = true;
      this.unlock_condition = function() {};
      this.buy = function() {
        if (this.locked || basedata.bloons < this.cost) {
          return false;
        }
        basedata.bloons -= this.cost;
        this.bought = true;
        return recalc(); // everything you buy has recalculatory effects.
      };
      items[name] = this;
      item_ids[id] = this;
      itemlist.push(this);
    }

  };

  number_format_load_codes = {
    "0": "full",
    "1": "small",
    "2": "scientific",
    "3": "engineering"
  };

  sanitize_number_format = function(format) {
    return number_format_load_codes[format] || (format === "full" || format === "small" || format === "scientific" || format === "engineering" ? format : "full");
  };

  load_save_from_local_storage = function() {
    var error, generator, k, len2, save_data;
    if (window.localStorage.hasOwnProperty("gc2.savefile") && window.localStorage["gc2.savefile"] !== "") {
      save_data = null;
      try {
        save_data = import_save(b64_to_sstr(window.localStorage["gc2.savefile"]));
      } catch (error1) {
        error = error1;
        console.warn("Could not load local save; clearing invalid save data.", error);
        window.localStorage["gc2.savefile"] = "";
        return;
      }
      if (!save_data) {
        return;
      }
      last_update_time.setTime(save_data["save_time"].getTime());
      if (save_data["play_time"] !== -1) {
        basedata.game_started = true;
        basedata.play_time = save_data["play_time"];
      }
      basedata.total_play_time = save_data["total_play_time"];
      basedata.bloons = save_data["bloons"];
      basedata.total_bloons = save_data["total_bloons"];
      basedata.total_total_bloons = save_data["total_total_bloons"];
      basedata.clicks = save_data["clicks"];
      basedata.total_clicks = save_data["total_clicks"];
      bloon.gain_exp(save_data["bloon_exp"]);
      sliggoo.gain_exp(save_data["sliggoo_exp"]);
      goodra.gain_exp(save_data["goodra_exp"]);
      basedata.sliggoo_gpsmult = 1.0 + 0.1 * sliggoo.level;
      bloon.level_cap = 1000 + goodra.level;
      for (k = 0, len2 = generators.length; k < len2; k++) {
        generator = generators[k];
        if (save_data.generators[generator.name]) {
          generator.count = save_data.generators[generator.name].count;
          generator.level = save_data.generators[generator.name].level;
        } else {
          generator.count = 0;
          generator.level = 1;
        }
        generator.cost = generator.cost_f(generator.count);
        generator.lvup_cost = generator.base_cost * 100 * Math.pow(1.35, generator.level - 1);
      }
      recalc();
      $("#settings_audio").prop("checked", settings.audio);
      $("#settings_music").prop("checked", settings.music);
      $("#settings_number_format").val(settings.number_format);
      battle.render();
      return update_all_numbers();
    }
  };

  import_save = function(str) {
    var version;
    version = str.split("||", 1)[0];
    if (version === "0.12") {
      return _import_save_0_10(str);
    } else if (version === "0.11") {
      return _import_save_0_10(str);
    } else if (version === "0.10") {
      return _import_save_0_10(str);
    } else if (version === "0.05") {
      return _import_save_0_05(str);
    } else {
      return null;
    }
  };

  //#########
  // actual import methods
  //#########

  // save file version 0.10
  _import_save_0_10 = function(str) {
    var d02_basedata, d03_bloonstats, d04_generators, d05_upgrades, d05_upgrades_bought, d05_upgrades_unlocked, d07_settings, d08_battle, data, datum, gen_data, generator_names, i, id, k, l, legacy_generator_names, ref, save, save_time;
    save = {};
    data = str.split("||");
    save_time = new Date();
    save_time.setTime(parseInt(data[1]));
    save["save_time"] = save_time;
    d02_basedata = data[2].split("|");
    save["play_time"] = parseFloat(d02_basedata[0]);
    save["total_play_time"] = parseFloat(d02_basedata[1]);
    save["bloons"] = parseFloat(d02_basedata[2]);
    save["total_bloons"] = parseFloat(d02_basedata[3]);
    save["total_total_bloons"] = parseFloat(d02_basedata[4]);
    save["clicks"] = parseFloat(d02_basedata[5]);
    save["total_clicks"] = parseFloat(d02_basedata[6]);
    d03_bloonstats = data[3].split("|");
    save["bloon_exp"] = parseInt(d03_bloonstats[0]);
    save["sliggoo_exp"] = parseInt(d03_bloonstats[1]);
    save["goodra_exp"] = parseInt(d03_bloonstats[2]);
    generator_names = ["cursor", "monkey", "tackshooter", "snipermonkey", "bombshooter", "boomerangthrower", "gluegunner", "icetower", "ninjamonkey", "monkeybuccaneer", "monkeyapprentice", "monkeysub", "monkeyace", "spikefactory", "monkeyengineer", "supermonkey"];
    legacy_generator_names = ["cursor", "monkey", "daycare", "reserve", "farm", "fountain", "cave", "trench", "arceus", "rngabuser", "cloninglab", "church", "gcminer", "photoncollider", "monkeyengineer", "supermonkey"];
    gen_data = {};
    d04_generators = data[4].split("|");
    for (i = k = 0, ref = Math.min(generator_names.length, d04_generators.length) - 1; (0 <= ref ? k <= ref : k >= ref); i = 0 <= ref ? ++k : --k) {
      datum = d04_generators[i].split(",");
      gen_data[generator_names[i]] = {
        count: parseInt(datum[0]),
        level: parseInt(datum[1])
      };
      if (legacy_generator_names[i] !== generator_names[i]) {
        gen_data[legacy_generator_names[i]] = gen_data[generator_names[i]];
      }
    }
    save["generators"] = gen_data;
    d05_upgrades = data[5].split("|");
    d05_upgrades_bought = sstr_to_bitfield(d05_upgrades[0]);
    d05_upgrades_unlocked = sstr_to_bitfield(d05_upgrades[1]);
    for (id = l = 1; l <= 250; id = ++l) {
      if (item_ids[id]) {
        if (d05_upgrades_unlocked[id - 1] === "1") {
          item_ids[id].locked = false;
          if (d05_upgrades_bought[id - 1] === "1") {
            item_ids[id].bought = true;
          }
        }
      }
    }
    if (data[6]) {
      d07_settings = data[6].split("|");
      settings.audio = d07_settings[0] !== "0";
      settings.music = d07_settings[1] !== "0";
      settings.number_format = sanitize_number_format(d07_settings[2] || "0");
    }
    if (data[7]) {
      d08_battle = data[7].split("|");
      battle.defeated = parseInt(d08_battle[0]) || 0;
      battle.current_index = parseInt(d08_battle[1]) || battle.defeated || 0;
      if (battle.defeated >= battle.bloons.length) {
        battle.current_index = battle.bloons.length;
      } else {
        battle.current_index = Math.min(battle.current_index, battle.bloons.length);
      }
      battle.eternal_stage = parseInt(d08_battle[2]) || Math.max(0, battle.defeated - battle.bloons.length);
      battle.active = false;
      battle.recalculate_rewards();
    }
    return save;
  };

  // save file version 0.05
  _import_save_0_05 = function(str) {
    var d02_basedata, d03_bloonstats, d04_generators, data, datum, gen_data, generator_names, i, k, legacy_generator_names, ref, save, save_time;
    save = {};
    data = str.split("||", 5);
    save_time = new Date();
    save_time.setTime(parseInt(data[1]));
    save["save_time"] = save_time;
    d02_basedata = data[2].split("|");
    save["play_time"] = parseFloat(d02_basedata[0]);
    save["total_play_time"] = parseFloat(d02_basedata[1]);
    save["bloons"] = parseFloat(d02_basedata[2]);
    save["total_bloons"] = parseFloat(d02_basedata[3]);
    save["total_total_bloons"] = parseFloat(d02_basedata[4]);
    save["clicks"] = parseFloat(d02_basedata[5]);
    save["total_clicks"] = parseFloat(d02_basedata[6]);
    d03_bloonstats = data[3].split("|");
    save["bloon_exp"] = parseInt(d03_bloonstats[0]);
    save["sliggoo_exp"] = parseInt(d03_bloonstats[1]);
    save["goodra_exp"] = parseInt(d03_bloonstats[2]);
    generator_names = ["cursor", "monkey", "tackshooter", "snipermonkey", "bombshooter", "boomerangthrower", "gluegunner", "icetower", "ninjamonkey", "monkeybuccaneer", "monkeyapprentice", "monkeysub", "monkeyace", "spikefactory", "monkeyengineer", "supermonkey"];
    legacy_generator_names = ["cursor", "monkey", "daycare", "reserve", "farm", "fountain", "cave", "trench", "arceus", "rngabuser", "cloninglab", "church", "gcminer", "photoncollider", "monkeyengineer", "supermonkey"];
    gen_data = {};
    d04_generators = data[4].split("|");
    for (i = k = 0, ref = Math.min(generator_names.length, d04_generators.length) - 1; (0 <= ref ? k <= ref : k >= ref); i = 0 <= ref ? ++k : --k) {
      datum = d04_generators[i].split(",");
      gen_data[generator_names[i]] = {
        count: parseInt(datum[0]),
        level: parseInt(datum[1])
      };
      if (legacy_generator_names[i] !== generator_names[i]) {
        gen_data[legacy_generator_names[i]] = gen_data[generator_names[i]];
      }
    }
    save["generators"] = gen_data;
    return save;
  };

  update_numbers = function() {
    var bloon_str;
    bloon_str = reprnum(Math.floor(basedata.bloons), "long");
    $(".bloons").html(bloon_str);
    $("#stats_playtime").html(reprtime(basedata.play_time));
    $("#stats_bloons").html(reprnum(Math.floor(basedata.bloons), "long"));
    $("#stats_total_bloons").html(reprnum(Math.floor(basedata.total_bloons), "long"));
    $("#stats_exp").html(reprnum(Math.floor(bloon.exp)));
    $("#stats_exp_to_next_level").html(reprnum(bloon.next_lv_exp + bloon.lv_total_exp - Math.floor(bloon.exp)));
    if (shiny_bloon.time_left > 0) {
      if (shiny_bloon.effect === "raindance") {
        $("#rain_dance_time_left").html(reprsecs(shiny_bloon.time_left));
      } else if (shiny_bloon.effect === "clickmult") {
        $("#click_frenzy_time_left").html(reprsecs(shiny_bloon.time_left));
      }
    }
    return $("#level_progress").attr("value", bloon.exp - bloon.lv_total_exp);
  };

  update_all_numbers = function() {
    var generator, gps_str, item, k, l, len2, len3;
    // updates numbers other than just Bloon count and related stats.
    update_numbers();
    gps_str = reprnum(Math.round(basedata.gps * 10) / 10, "medium");
    $(".gps").html(gps_str);
    $("#stats_gps").html(gps_str);
    for (k = 0, len2 = generators.length; k < len2; k++) {
      generator = generators[k];
      $("#" + generator.name + "_cost").html(reprnum(Math.floor(generator.cost), "short"));
      if (indexOf.call(ngens, generator) >= 0) {
        if (generator.count > 0) {
          $("#" + generator.name + "_count").html("x" + reprnum(generator.count, "short"));
        } else {
          $("#" + generator.name + "_count").html("");
        }
      } else {
        $("#" + generator.name + "_count").html(reprnum(generator.count, "short"));
      }
      $(`#${generator.name}_gps`).html(reprnum(Math.round(generator.gps * 100) / 100, "medium"));
      $(`#${generator.name}_owned`).html(reprnum(generator.count, "short"));
      $(`#${generator.name}_tooltip_cost`).html(reprnum(Math.floor(generator.cost), "long"));
      $(`#${generator.name}_level`).html(reprnum(generator.level, "short"));
      $(`#${generator.name}_levelup_cost`).html(reprnum(generator.lvup_cost, "short"));
    }
    // special abbreviation code for cursors and monkeys
    if (("" + gens["cursor"].count).length >= langs[lang].cursor_abbrev_length + 2) {
      $("#cursor_counter").html("");
    } else if (("" + gens["cursor"].count).length >= langs[lang].cursor_abbrev_length) {
      $("#cursor_counter").html(langs[lang].cursor_counter_short);
    } else {
      $("#cursor_counter").html(langs[lang].cursor_counter);
    }
    if (("" + gens["monkey"].count).length >= langs[lang].monkey_abbrev_length + 2) {
      $("#monkey_counter").html("");
    } else if (("" + gens["monkey"].count).length >= langs[lang].monkey_abbrev_length) {
      $("#monkey_counter").html(langs[lang].monkey_counter_short);
    } else {
      $("#monkey_counter").html(langs[lang].monkey_counter);
    }
    for (l = 0, len3 = itemlist.length; l < len3; l++) {
      item = itemlist[l];
      if (item.locked && item.unlock_condition()) {
        item.locked = false;
        // create the item in HTML.
        $("#items").append(`<div class='item' id='${item.name}'> ${item.display_name || item.name} </div>`);
        // create the tooltip
        $("#tooltips").append(`<div class='item-tooltip' id='${item.name}_tooltip'></div>`);
        $(`#${item.name}_tooltip`).append(`<p id='${item.name}_description'>` + (langs[lang][`${item.name}_description`] || item.description) + "</p>" + `<br /> Cost: <span class='tooltip-gps' id='${item.name}_tooltip_cost'></span> Bloons <hr />` + `<span id='${item.name}_flavourtext'>` + (langs[lang][`${item.name}_caption`] || item.caption) + "</span>");
        $(`#${item.name}_tooltip_cost`).html(reprnum(Math.floor(item.cost), "long"));
        $(`#${item.name}`).qtip({
          content: {
            title: item.display_name || langs[lang][`${item.name}_name`] || item.name,
            text: $($(`#${item.name}_tooltip`)[0])
          },
          style: {
            classes: "qtip-dark",
            width: 300
          },
          position: {
            my: $(window).width() > 1024 ? "right center" : "bottom left",
            at: $(window).width() > 1024 ? "left center" : "top left",
            viewport: $(window)
          },
          show: {
            delay: 0
          },
          hide: {
            delay: 100
          }
        });
        $(`#${item.name}`).click((function(name) {
          return function() {
            if (items[name].buy()) {
              return $(`#${name}`).hide();
            }
          };
        })(item.name));
      }
    }
    if (bloon.level === bloon.level_cap) {
      $("#stats_next_level_row").hide();
    } else {
      $("#stats_next_level_row").show();
    }
    $(".level").html(reprnum(bloon.level, "short"));
    $("#level_progress").attr("max", bloon.next_lv_exp);
    return $("#stats_next_level").html(reprnum(bloon.level + 1, "short"));
  };

  update_language = function() {
    regenerate_tooltips();
    return update_all_numbers();
  };

  regenerate_tooltips = function() {
    var generator, k, l, len2, len3;
    for (k = 0, len2 = generators.length; k < len2; k++) {
      generator = generators[k];
      $(`#${generator.name}`).unbind();
      if ($(window).width() >= 1024) {
        $(`#${generator.name}`).click((function(name) {
          return function() {
            return gens[name].buy(1);
          };
        })(generator.name));
      }
    }
    // if on a mobile platform, clicking to show tooltips shouldn't autobuy.
    $("#tooltips").empty();
    $(".qtip").empty();
    for (l = 0, len3 = generators.length; l < len3; l++) {
      generator = generators[l];
      // tooltips are annoying because of this. >_>
      $(`#${generator.name}_description`).html(langs[lang][`${generator.name}_description`] || generator.description);
      $("#tooltips").append(`<div class='generator-tooltip' id='${generator.name}_tooltip'></div>`);
      $(`#${generator.name}_tooltip`).append(`<span id='${generator.name}_description'>` + (langs[lang][`${generator.name}_description`] || generator.description) + "</span>" + `<hr /> <span class='lang_tooltip_gps_pre'>Each one produces </span> <span class='tooltip-gps' id='${generator.name}_gps'></span> <span class='lang_tooltip_gps_post'> Bloons per second</span> <br /> <span class='lang_tooltip_owned_pre'>You own </span> <span class='tooltip-gps' id='${generator.name}_owned'></span> <span class='lang_tooltip_owned_post'></span> <br /> <span class='lang_tooltip_cost_pre'>To buy one costs </span> <span class='tooltip-gps' id='${generator.name}_tooltip_cost'></span> <span class='lang_tooltip_cost_post'> Bloons</span> <br /> <button class='tooltip-buy-button lang_tooltip_buy1' id='${generator.name}_buy1'>Buy 1</button> <button class='tooltip-buy-button lang_tooltip_buy10' id='${generator.name}_buy10'>Buy 10</button> <button class='tooltip-buy-button lang_tooltip_buy100' id='${generator.name}_buy100'>Buy 100</button> <button class='tooltip-buy-button lang_tooltip_sell1' id='${generator.name}_sell1'>Sell 1</button> <hr /> <span class='lang_tooltip_level_pre'>Level </span> <span class='tooltip-gps' id='${generator.name}_level'></span> <span class='lang_tooltip_level_post'></span> <button id='${generator.name}_levelup' class='tooltip-buy-button'>Level up for <span id='${generator.name}_levelup_cost'></span></button>`);
      $(`#${generator.name}`).qtip({
        content: {
          title: langs[lang][`${generator.name}_name`] || generator.display_name || generator.name,
          text: $($(`#${generator.name}_tooltip`)[0])
        },
        style: {
          classes: "qtip-dark",
          width: 300
        },
        position: {
          my: $(window).width() > 1024 ? "right center" : "bottom left",
          at: $(window).width() > 1024 ? "left center" : "top left",
          viewport: $(window)
        },
        show: {
          delay: 0
        },
        hide: {
          fixed: true,
          delay: 100
        }
      });
      $(`#${generator.name}_buy1`).click((function(name) {
        return function() {
          return gens[name].buy(1);
        };
      })(generator.name));
      $(`#${generator.name}_buy10`).click((function(name) {
        return function() {
          return gens[name].buy(10);
        };
      })(generator.name));
      $(`#${generator.name}_buy100`).click((function(name) {
        return function() {
          return gens[name].buy(100);
        };
      })(generator.name));
      $(`#${generator.name}_sell1`).click((function(name) {
        return function() {
          return gens[name].sell(1);
        };
      })(generator.name));
      $(`#${generator.name}_levelup`).click((function(name) {
        return function() {
          return gens[name].levelup();
        };
      })(generator.name));
    }
    $(".lang_tooltip_gps_pre").html(langs[lang]["tooltip_gps_pre"]);
    $(".lang_tooltip_gps_post").html(langs[lang]["tooltip_gps_post"]);
    $(".lang_tooltip_owned_pre").html(langs[lang]["tooltip_owned_pre"]);
    $(".lang_tooltip_owned_post").html(langs[lang]["tooltip_owned_post"]);
    $(".lang_tooltip_cost_pre").html(langs[lang]["tooltip_cost_pre"]);
    $(".lang_tooltip_cost_post").html(langs[lang]["tooltip_cost_post"]);
    $(".lang_tooltip_buy1").html(langs[lang]["tooltip_buy1"]);
    $(".lang_tooltip_buy10").html(langs[lang]["tooltip_buy10"]);
    $(".lang_tooltip_buy100").html(langs[lang]["tooltip_buy100"]);
    return $(".lang_tooltip_sell1").html(langs[lang]["tooltip_sell1"]);
  };

  $(window).resize(function() {
    regenerate_tooltips();
    return update_all_numbers();
  });

  // main game loop
  last_update_time = new Date();

  updateF = function(ms) {
    basedata.update(ms);
    battle.update(ms);
    shiny_bloon.update(ms);
    update_numbers(ms);
    return animate_plus_markers(ms);
  };

  update = function() {
    var ms, new_update_time;
    new_update_time = new Date();
    ms = new_update_time.getTime() - last_update_time.getTime();
    last_update_time.setTime(new_update_time.getTime());
    return updateF(ms);
  };

  plus_marker_id = 0;

  plus_marker_anims = 1000;

  plus_marker_distance = 100;

  plus_marker_origradius = 20;

  PlusMarker = class PlusMarker {
    constructor(caption, x, y, anims) {
      this.id = plus_marker_id;
      plus_marker_id += 1;
      plus_markers[this.id] = this;
      this.caption = caption;
      this.init_anims = anims ? anims : plus_marker_anims;
      this.anims = this.init_anims;
      $("#gamearea").append(`<div class='plus_marker' id='plus_marker_${this.id}'>${this.caption}</div>`);
      this.orig_x = Math.max(0, Math.min($(window).width() - $(`#plus_marker_${this.id}`).width(), x - $(`#plus_marker_${this.id}`).width() / 2));
      this.orig_y = Math.max(0, Math.min($(window).height() - $(`#plus_marker_${this.id}`).height(), y - $(`#plus_marker_${this.id}`).height() / 2));
      this.x = this.orig_x;
      this.y = this.orig_y;
      this.opacity = 1;
      $(`#plus_marker_${this.id}`).css({
        left: this.x,
        top: this.y,
        opacity: this.opacity
      });
    }

    update(ms) {
      var move_fraction;
      this.anims -= ms;
      if (this.anims <= 0) {
        $(`#plus_marker_${this.id}`).remove();
        delete plus_markers[this.id];
        return;
      }
      move_fraction = this.anims / this.init_anims;
      this.y = Math.max(0, this.orig_y - plus_marker_distance + plus_marker_distance * move_fraction * move_fraction);
      this.opacity = move_fraction;
      return $(`#plus_marker_${this.id}`).css({
        left: this.x,
        top: this.y,
        opacity: this.opacity
      });
    }

  };

  plus_markers = {};

  this.plus_markers = plus_markers;

  animate_plus_markers = function(ms) {
    var id, plus_marker, results;
    results = [];
    for (id in plus_markers) {
      if (!hasProp.call(plus_markers, id)) continue;
      plus_marker = plus_markers[id];
      results.push(plus_marker.update(ms));
    }
    return results;
  };

  recalc = function() {
    recalc_gps();
    recalc_gpc();
    return update_all_numbers();
  };

  recalc_gps = function() {
    var item, k, l, len2, len3, len4, m, new_gps;
    // account for base gps upgrades first.
    gens["monkey"].base_gps = 1.0;
    if (items["ball01"].bought) {
      gens["monkey"].base_gps += 0.5;
    }
    if (items["ball02"].bought) {
      gens["monkey"].base_gps += 1.0;
    }
    if (items["ball99"].bought) {
      gens["monkey"].base_gps += 100.0;
    }
    for (k = 0, len2 = generators.length; k < len2; k++) {
      gen = generators[k];
      // reset the variables for calculation
      gen.level_mult = Math.pow(1.3, gen.level - 1);
      gen.gps = gen.base_gps * gen.level_mult;
    }
// tiered generator upgrades
    for (l = 0, len3 = itemlist.length; l < len3; l++) {
      item = itemlist[l];
      if (item.bought && item.generator_name && gens[item.generator_name]) {
        gens[item.generator_name].gps *= item.bps_mult;
      }
    }
    basedata.expps = 0.2 * gens["cursor"].count;
    new_gps = 0;
    for (m = 0, len4 = generators.length; m < len4; m++) {
      gen = generators[m];
      new_gps += gen.count * gen.gps;
    }
    new_gps *= basedata.sliggoo_gpsmult;
    new_gps *= basedata.raindance_mult;
    new_gps *= battle.bps_mult;
    return basedata.gps = new_gps;
  };

  recalc_gpc = function() {
    var k, len2, new_gpc;
    new_gpc = 0;
    new_gpc += bloon.level;
    for (k = 0, len2 = generators.length; k < len2; k++) {
      gen = generators[k];
      if (items["gcm1"].bought) {
        new_gpc += gen.count * (bloon.level - 5) * 0.1;
      }
      if (items["gcm2"].bought) {
        new_gpc += gen.count * (bloon.level - 10) * 0.2;
      }
      if (items["gcm3"].bought) {
        new_gpc += gen.count * (bloon.level - 20) * 0.5;
      }
      if (items["gcm4"].bought) {
        new_gpc += gen.count * (bloon.level - 40) * 2.0;
      }
      if (items["gcm5"].bought) {
        new_gpc += gen.count * (bloon.level - 80) * 10.0;
      }
    }
    new_gpc *= Math.pow(1.1, gens["cursor"].level - 1);
    new_gpc *= basedata.raindance_mult;
    new_gpc *= basedata.frenzy_clickmult;
    new_gpc *= battle.tap_mult;
    return basedata.gpc = new_gpc;
  };

  number_format_save_codes = {
    full: "0",
    small: "1",
    scientific: "2",
    engineering: "3"
  };

  save_to_local_storage = function() {
    return window.localStorage["gc2.savefile"] = sstr_to_b64(export_save());
  };

  hexstr = "0123456789abcdef";

  bitmap = {
    "0": "0000",
    "1": "0001",
    "2": "0010",
    "3": "0011",
    "4": "0100",
    "5": "0101",
    "6": "0110",
    "7": "0111",
    "8": "1000",
    "9": "1001",
    "a": "1010",
    "b": "1011",
    "c": "1100",
    "d": "1101",
    "e": "1110",
    "f": "1111"
  };

  bitfield_to_sstr = function(bitfield) {
    var a, i, k, l, len, lenstr, output, ref, ref1;
    output = "";
    while (bitfield.length % 8 !== 0) {
      bitfield += "0";
    }
    len = bitfield.length / 8;
    lenstr = "" + len;
    for (i = k = 1, ref = lenstr.length; (1 <= ref ? k <= ref : k >= ref); i = 1 <= ref ? ++k : --k) {
      output += "`";
    }
    output += lenstr;
    for (a = l = 0, ref1 = bitfield.length - 1; l <= ref1; a = l += 4) {
      output += hexstr[parseInt(bitfield.substr(a, 4), 2)];
    }
    return output;
  };

  sstr_to_bitfield = function(sstr) {
    var char, k, len, len2, output;
    output = "";
    len = 0;
    for (k = 0, len2 = sstr.length; k < len2; k++) {
      char = sstr[k];
      if (char === "`") {
        len += 1;
      } else if (len > 0) {
        len -= 1;
      } else {
        output += bitmap[char];
      }
    }
    return output;
  };

  export_save = function() {
    var d01_version, d02_savetime, d03_basedata, d04_bloonstats, d05_generators, d06_upgrades, d07_settings, d08_battle;
    d01_version = "0.12";
    d02_savetime = "" + new Date().getTime();
    // GPS, EXPPS, and GPC are recalculable, and so are not included here.
    d03_basedata = [basedata.game_started ? repr_sstr(basedata.play_time) : "-1", repr_sstr(basedata.total_play_time), repr_sstr(Math.floor(basedata.bloons)), repr_sstr(Math.floor(basedata.total_bloons)), repr_sstr(Math.floor(basedata.total_total_bloons)), repr_sstr(basedata.clicks), repr_sstr(basedata.total_clicks)].join("|");
    d04_bloonstats = [repr_sstr(Math.floor(bloon.exp)), repr_sstr(Math.floor(sliggoo.exp)), repr_sstr(Math.floor(goodra.exp))].join("|");
    d05_generators = (function() {
      var gen_stat_string, gen_stats, generator, k, len2;
      gen_stats = [];
      for (k = 0, len2 = generators.length; k < len2; k++) {
        generator = generators[k];
        gen_stat_string = [generator.count, generator.level].join(",");
        gen_stats.push(gen_stat_string);
      }
      return gen_stats.join("|");
    })();
    d06_upgrades = (function() {
      var i, k, upgrade_bought, upgrade_unlocked;
      upgrade_bought = "";
      upgrade_unlocked = "";
      for (i = k = 1; k <= 250; i = ++k) {
        if (item_ids[i] && item_ids[i].bought) {
          upgrade_bought += "1";
        } else {
          upgrade_bought += "0";
        }
        if (item_ids[i] && !item_ids[i].locked) {
          upgrade_unlocked += "1";
        } else {
          upgrade_unlocked += "0";
        }
      }
      return bitfield_to_sstr(upgrade_unlocked) + "|" + bitfield_to_sstr(upgrade_bought);
    })();
    d07_settings = [(settings.audio ? "1" : "0"), (settings.music ? "1" : "0"), number_format_save_codes[settings.number_format] || number_format_save_codes.full].join("|");
    d08_battle = [battle.defeated, battle.current_index, battle.eternal_stage].join("|");
    return [d01_version, d02_savetime, d03_basedata, d04_bloonstats, d05_generators, d06_upgrades, d07_settings, d08_battle].join("||");
  };

  init_cooldown_time = 200000;

  shiny_bloon = {
    enabled: false,
    appeared: false,
    opacity: 0,
    x: 0,
    y: 0,
    effect: "none", // one of "bloons", "raindance", "clickmult", "levelup"
    time_left: 0, // for timed effects.
    cooldown_time: init_cooldown_time, // for cooldown time.
    clicks: 0,
    total_clicks: 0,
    update: function(ms) {
      var spinner;
      if (!this.enabled) {
        return this.enabled = true; // Prevent a shiny Bloon from "always" appearing upon loading a new window due to the long wait time.
      } else if (this.time_left > 0) {
        this.time_left -= ms;
        if (this.time_left <= 0) {
          // cancel out the initial effect.
          if (this.effect === "raindance") {
            basedata.raindance_mult = 1.0;
            $("#shiny_bloon_rain_dance").hide();
            recalc();
          }
          if (this.effect === "clickmult") {
            basedata.frenzy_clickmult = 1.0;
            $("#shiny_bloon_click_frenzy").hide();
            return recalc();
          }
        }
      } else if (this.appeared) {
        if (this.opacity < 1) {
          this.opacity = Math.min(1, this.opacity + ms / 2000);
          return $("#shiny_bloon").css({
            opacity: this.opacity // if yet to appear
          });
        }
      } else {
        if (this.cooldown_time > 0) {
          return this.cooldown_time -= ms;
        } else if (Math.random() > Math.pow(0.995, ms / 1000)) {
          this.appeared = true;
          this.x = Math.random() * ($(window).width() - $("#shiny_bloon").width());
          this.y = Math.random() * ($(window).height() - $("#shiny_bloon").height());
          spinner = Math.random();
          if (spinner < 0.6) {
            this.effect = "bloons";
          } else if (spinner < 0.935) {
            this.effect = "raindance";
          } else if (spinner < 0.985) {
            this.effect = "clickmult";
          } else if (spinner < 0.9945) {
            this.effect = "bloons";
          } else if (spinner < 0.999) {
            this.effect = "bloons";
          } else {
            this.effect = "bloons";
          }
          $("#shiny_bloon").show();
          $("#shiny_bloon").css({
            left: this.x,
            top: this.y,
            opacity: 0
          });
          return $("#shiny_bloon").click((e) => {
            return this.click(e.pageX, e.pageY);
          });
        }
      }
    },
    click: function(x, y) {
      var gain, shiny_plus_marker;
      $("#shiny_bloon").unbind();
      $("#shiny_bloon").hide();
      this.appeared = false;
      this.opacity = 0;
      basedata.clicks += 1;
      basedata.total_clicks += 1;
      this.cooldown_time = init_cooldown_time;
      if (this.effect === "bloons") {
        // award = 120 seconds of Bloon production + 200 clicks worth of Bloons
        gain = basedata.gps * 120 + basedata.gpc * 200;
        shiny_plus_marker = new PlusMarker(`Bonus! +${reprnum(Math.floor(gain), "long")} Bloons!`, x, y, 3000);
        basedata.earn(gain);
        return gain;
      } else if (this.effect === "raindance") {
        this.time_left = 70400;
        basedata.raindance_mult = 12.0;
        recalc();
        $("#shiny_bloon_rain_dance").show();
        return shiny_plus_marker = new PlusMarker("Rain Dance! Production x12 for 70.4 seconds!", x, y, 3000);
      } else if (this.effect === "clickmult") {
        this.time_left = 7040;
        basedata.frenzy_clickmult = 704.0;
        recalc();
        $("#shiny_bloon_click_frenzy").show();
        return shiny_plus_marker = new PlusMarker("Click Frenzy! Clicking x704 for 7.04 seconds!", x, y, 3000);
      }
    }
  };

  this.click_on_shiny_bloon = shiny_bloon.click;

  start_if_loaded = function() {
    init_input();
    change_language(lang);
    load_save_from_local_storage();
    setInterval(update, 20);
    return setInterval(save_to_local_storage, 10000);
  };

  startup = function() {
    return start_if_loaded();
  };

  $(document).ready(startup);

  // GCM = generator click multiplier, I think?
  gcm1 = new Item("gcm1", 1);

  gcm1.unlock_condition = function() {
    return bloon.level >= 5;
  };

  gcm1.cost = 1e4;

  gcm2 = new Item("gcm2", 2);

  gcm2.unlock_condition = function() {
    return bloon.level >= 10;
  };

  gcm2.cost = 1e5;

  gcm3 = new Item("gcm3", 3);

  gcm3.unlock_condition = function() {
    return bloon.level >= 20;
  };

  gcm3.cost = 1e7;

  gcm4 = new Item("gcm4", 4);

  gcm4.unlock_condition = function() {
    return bloon.level >= 40;
  };

  gcm4.cost = 1e10;

  gcm5 = new Item("gcm5", 5);

  gcm5.unlock_condition = function() {
    return bloon.level >= 80;
  };

  gcm5.cost = 1e14;

  click1 = new Item("click1", 6);

  click1.unlock_condition = function() {
    return bloon.level >= 100;
  };

  click1.cost = 1e16;

  // dart monkey base upgrades
  ball01 = new Item("ball01", 8);

  ball01.unlock_condition = function() {
    return bloon.level >= 10 && gens["monkey"].count >= 10;
  };

  ball01.cost = 1e4;

  ball02 = new Item("ball02", 9);

  ball02.unlock_condition = function() {
    return bloon.level >= 30 && gens["monkey"].count >= 50;
  };

  ball02.cost = 1e8;

  ball99 = new Item("ball99", 10);

  ball99.unlock_condition = function() {
    return bloon.level >= 100;
  };

  ball99.cost = 1e15;

  // 11 tiered BpS upgrades for every non-cursor monkey/tower type.
  generator_upgrade_defs = [
    {
      tier: 1,
      bps: 2,
      cost_mult: 20,
      level: 10,
      type: "Minor",
      suffix: "Focused Training"
    },
    {
      tier: 2,
      bps: 2,
      cost_mult: 300,
      level: 25,
      type: "Minor",
      suffix: "Sharper Instincts"
    },
    {
      tier: 3,
      bps: 2,
      cost_mult: 4000,
      level: 50,
      type: "Minor",
      suffix: "Veteran Drills"
    },
    {
      tier: 4,
      bps: 2,
      cost_mult: 60000,
      level: 75,
      type: "Minor",
      suffix: "Elite Discipline"
    },
    {
      tier: 5,
      bps: 4,
      cost_mult: 900000,
      level: 100,
      type: "Major",
      suffix: "Mastery"
    },
    {
      tier: 6,
      bps: 2,
      cost_mult: 12500000,
      level: 150,
      type: "Minor",
      suffix: "Expert Coordination"
    },
    {
      tier: 7,
      bps: 2,
      cost_mult: 175000000,
      level: 200,
      type: "Minor",
      suffix: "Hyper Practice"
    },
    {
      tier: 8,
      bps: 5,
      cost_mult: 2500000000,
      level: 250,
      type: "Major",
      suffix: "Paragon Assault"
    },
    {
      tier: 9,
      bps: 2,
      cost_mult: 35000000000,
      level: 300,
      type: "Minor",
      suffix: "Relentless Output"
    },
    {
      tier: 10,
      bps: 4,
      cost_mult: 500000000000,
      level: 350,
      type: "Major",
      suffix: "Ascended Arsenal"
    },
    {
      tier: 11,
      bps: 2,
      cost_mult: 7500000000000,
      level: 400,
      type: "Minor",
      suffix: "Endless Barrage"
    }
  ];

  for (k = 0, len2 = generators.length; k < len2; k++) {
    gen = generators[k];
    if (gen.name !== "cursor") {
      for (l = 0, len3 = generator_upgrade_defs.length; l < len3; l++) {
        def = generator_upgrade_defs[l];
        (function(gen, def) {
          var item;
          item = new Item(`${gen.name}_tier${def.tier}`, 51 + (generators.indexOf(gen) - 1) * 11 + def.tier);
          item.generator_name = gen.name;
          item.bps_mult = def.bps;
          item.display_name = `${gen.display_name} ${def.suffix}`;
          item.description = `Tier ${def.tier} (${def.type}): ${gen.display_name} BpS is multiplied by <b>${def.bps}x</b>. Requires level ${def.level}.`;
          item.caption = `${def.type} upgrade for ${gen.display_name}.`;
          item.unlock_condition = function() {
            return gen.level >= def.level;
          };
          return item.cost = gen.base_cost * def.cost_mult;
        })(gen, def);
      }
    }
  }

  youngsterpocalypse = {
    started: false,
    time_left: 259200000 //  72 hours in milliseconds
  };

  this.export_save = save_to_local_storage;

  this.import_save = load_save_from_local_storage;

  this.gens = gens;

  this.items = items;

  this.update_language = update_language;

  this.bitfield_to_sstr = bitfield_to_sstr;

}).call(this);
